In [86]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
%matplotlib inline

In [87]:
artworks = pd.read_csv('Artworks.csv')


In [88]:
artworks = artworks[['Artist', 'Nationality', 'Gender', 'Date', 'Department',
                    'DateAcquired', 'URL', 'ThumbnailURL', 'Height (cm)', 'Width (cm)']]

# Convert URL's to booleans.
artworks['URL'] = artworks['URL'].notnull()
artworks['ThumbnailURL'] = artworks['ThumbnailURL'].notnull()

# Drop films and some other tricky rows.
artworks = artworks[artworks['Department']!='Film']
artworks = artworks[artworks['Department']!='Media and Performance Art']
artworks = artworks[artworks['Department']!='Fluxus Collection']

# Drop missing data.
artworks = artworks.dropna()

artworks['DateAcquired'] = pd.to_datetime(artworks.DateAcquired)
artworks['YearAcquired'] = artworks.DateAcquired.dt.year
artworks['YearAcquired'].dtype
artworks.loc[artworks['Gender'].str.contains('\) \('), 'Gender'] = '\(multiple_persons\)'
artworks.loc[artworks['Nationality'].str.contains('\) \('), 'Nationality'] = '\(multiple_nationalities\)'
artworks.loc[artworks['Artist'].str.contains(','), 'Artist'] = 'Multiple_Artists'

# Convert dates to start date, cutting down number of distinct examples.
artworks['Date'] = pd.Series(artworks.Date.str.extract(
    '([0-9]{4})', expand=False))[:-1]
artworks = artworks.sample(20000, random_state=43)

# Final column drops and NA drop.
X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date'], 1)

# Create dummies separately.
artists = pd.get_dummies(artworks.Artist)
nationalities = pd.get_dummies(artworks.Nationality)
dates = pd.get_dummies(artworks.Date)

# Concat with other variables, but artists slows this wayyyyy down so we'll keep it out for now
X = pd.get_dummies(X, sparse=True)
X = pd.concat([X, nationalities, dates], axis=1)

Y = artworks.Department

In [89]:
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 1000 perceptron layer.
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [90]:
mlp.score(X,Y)

0.6576

In [91]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.59095452, 0.49425287, 0.2448112 , 0.51987997, 0.13381691])

In [92]:
#add layers,change alpha,power t up
mlp = MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(100,24,10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.6,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(100, 24, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.6,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [93]:
mlp.score(X,Y)

0.68345

In [94]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.62093953, 0.63668166, 0.51987997, 0.26381595, 0.49624812])

In [95]:
#.alpha lower,power t lower, 2 layers

In [96]:
mlp = MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(1000,200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.4,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(1000, 200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.4,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [97]:
mlp.score(X,Y)

0.64915

In [98]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.66091954, 0.56996502, 0.60765191, 0.29757439, 0.13181591])

In [99]:
mlp = MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.85,
       beta_2=0.997, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(400,125), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.85,
       beta_2=0.997, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(400, 125), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [100]:
mlp.score(X,Y)

0.6591

In [101]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.64567716, 0.59770115, 0.5263816 , 0.10802701, 0.60205103])

In [102]:
artworks['Width (cm)'] = np.where(artworks['Width (cm)'] == 0,0,np.log(artworks['Width (cm)']))
artworks['Height (cm)'] = np.where(artworks['Height (cm)'] == 0,0,np.log(artworks['Height (cm)']))

/root/.pyenv/versions/jupyter3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.
/root/.pyenv/versions/jupyter3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


In [103]:
artworks.head()

Artist                 Nationality                Gender  \
49641    Josef Koudelka                     (Czech)                (Male)   
33682     Henri Laurens                    (French)                (Male)   
82414      John Thomson                   (British)                (Male)   
52374      Vernon Heath                   (British)                (Male)   
50834  Multiple_Artists  \(multiple_nationalities\)  \(multiple_persons\)   

       Date   Department DateAcquired    URL  ThumbnailURL  Height (cm)  \
49641  1962  Photography   1971-05-04   True          True     3.072693   
33682  1917     Drawings   1976-06-02  False         False     3.517498   
82414  1877  Photography   1972-05-02  False         False     3.295837   
52374  1869  Photography   1990-12-13  False         False     3.998201   
50834  1869  Photography   1981-12-17  False         False     3.339322   

       Width (cm)  YearAcquired  
49641    3.475067          1971  
33682    3.194583          1976  
82414    2.954910          1972  
52374    4.204693          1990  
50834    3.663562          1981

As these models take forever to run, i wont try many other things.

In [104]:
 X = artworks.drop(['Department', 'DateAcquired', 'Artist', 'Nationality', 'Date','ThumbnailURL'], 1)

In [105]:
X.head()

Gender    URL  Height (cm)  Width (cm)  YearAcquired
49641                (Male)   True     3.072693    3.475067          1971
33682                (Male)  False     3.517498    3.194583          1976
82414                (Male)  False     3.295837    2.954910          1972
52374                (Male)  False     3.998201    4.204693          1990
50834  \(multiple_persons\)  False     3.339322    3.663562          1981

In [106]:
X.Gender = np.where(X.Gender == '(male)',1,0)
X.URL = np.where(X.URL == True,1,0)
X.head()

Gender  URL  Height (cm)  Width (cm)  YearAcquired
49641       0    1     3.072693    3.475067          1971
33682       0    0     3.517498    3.194583          1976
82414       0    0     3.295837    2.954910          1972
52374       0    0     3.998201    4.204693          1990
50834       0    0     3.339322    3.663562          1981

In [107]:
X = normalize(X)
#Sca

In [108]:
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
mlp.fit(X, Y)
print(mlp.score(X,Y))
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

0.5319


array([0.53448276, 0.52598701, 0.5223806 , 0.51987997, 0.54452226])

In [109]:
#add layers,change alpha,power t up
mlp = MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(100,24,10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.6,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(100, 24, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.6,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [110]:
mlp.score(X,Y)

0.53205

In [111]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.51974013, 0.51974013, 0.51987997, 0.51987997, 0.52001001])

In [112]:
#.alpha lower,power t lower, 2 layers

In [113]:
mlp = MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(1000,200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.4,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-07,
       hidden_layer_sizes=(1000, 200), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.4,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [114]:
mlp.score(X,Y)

0.53405

In [115]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.53248376, 0.52423788, 0.51987997, 0.51987997, 0.52001001])

In [116]:
mlp = MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.85,
       beta_2=0.997, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(400,125), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.001, batch_size='auto', beta_1=0.85,
       beta_2=0.997, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(400, 125), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [117]:
mlp.score(X,Y)

0.52645

In [118]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.52548726, 0.52473763, 0.51987997, 0.51987997, 0.52001001])

In [119]:
mlp = MLPClassifier(activation='relu', alpha=0.05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000,125), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000, 125), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [120]:
mlp.score(X,Y)

0.51985

In [121]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.51974013, 0.51974013, 0.51987997, 0.51987997, 0.52001001])

As these model take forever to run, I will not run any others, but in the first segment with not normalized dats, the scores were higher, but the cross validation was inconsistent indicating an overfit model. Increasing the alpha and decreasing the epsilon seemed to increase the score and the consistency. As other hyper parameters were tweaked, the accuracy fell.

Logging the Height and Width led to lower accuracy however the results were consistent. More adjustments and feature engineering may be necessary.

It also appears that the wider the layer, the more performant, perhaps more overfit

In [122]:
mlp = MLPClassifier(activation='relu', alpha=0.05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2000,1000), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(2000, 1000), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [123]:
mlp.score(X,Y)

0.51985

In [124]:
from sklearn.model_selection import cross_val_score
cross_val_score(mlp, X, Y, cv=5)

array([0.51974013, 0.51974013, 0.51987997, 0.51987997, 0.52001001])