In [382]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy
import math
%matplotlib inline

In [383]:
music = pd.DataFrame()
music['duration'] = [184, 134, 243, 186, 122, 197, 294, 382, 102, 264, 
                     205, 110, 307, 110, 397, 153, 190, 192, 210, 403,
                     164, 198, 204, 253, 234, 190, 182, 401, 376, 102]
music['loudness'] = [18, 34, 43, 36, 22, 9, 29, 22, 10, 24, 
                     20, 10, 17, 51, 7, 13, 19, 12, 21, 22,
                     16, 18, 4, 23, 34, 19, 14, 11, 37, 42]
music['jazz'] = [ 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
                  0, 1, 1, 0, 1, 1, 0, 1, 1, 1,
                  1, 1, 1, 1, 0, 0, 1, 1, 0, 0]

In [384]:
def jazz(target, p1, p2, new):
    df = pd.DataFrame()
    df['z'] =target
    df['dist'] = ((new[0] - p1)**2 + (new[1] - p2)**2)**.5
    res = df.dist.min()
    return df.loc[df.dist == res]['z']   

In [385]:
newsong = [17,394]
jazz(music.jazz,music.loudness, music.duration, newsong)

27    1
Name: z, dtype: int64

In [386]:
new = [29,179]
X = np.array(music[['loudness','duration']])
Y = music['jazz']
distances = []
for i in X:
    distance = np.sqrt((i[0]-new[0])**2 + (i[1]-new[1])**2)
    distances.append(distance)
    closest = distances.index(min(distances))
print(Y[closest])




0


In [387]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=1)
X = music[['loudness','duration']]
Y = music.jazz
neighbors.fit(X,Y)

neighbors.predict([[29,179]])

array([0])

In [388]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=1)
X = music[['loudness','duration']]
Y = music.jazz
neighbors.fit(X,Y)

neighbors.predict([[17,394]])

array([1])

In [389]:
def jazz(k,target, p1, p2, new):
    df = pd.DataFrame()
    df['z'] =target
    df['dist'] = ((new[0] - p1)**2 + (new[1] - p2)**2)**.5
    res = df.sort_values('dist')[0:k]
    prob = res['z'].sum()/k
    if prob > .5:
        return 'Jazz,'+' Conf by votes: {}'.format(prob)
    if prob < 5:
        return 'Rock'+' Conf by votes: {}'.format(prob)
    
    
    

In [390]:
newsong = [29, 400]
jazz(5,music.jazz,music.loudness, music.duration, newsong)

'Jazz, Conf by votes: 0.8'

In [396]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=5)
X = music[['loudness','duration']]
Y = music.jazz
neighbors.fit(X,Y)

print(neighbors.predict([[29,400]]))
print(neighbors.predict_proba([[29,400]]))

[1]
[[0.2 0.8]]


In [391]:
newsong = [34,173]
jazz(10,music.jazz,music.loudness, music.duration, newsong)

'Jazz, Conf by votes: 0.7'

In [392]:
newsong = [34,173]
jazz(1,music.jazz,music.loudness, music.duration, newsong)

'Rock Conf by votes: 0.0'

In [393]:
from sklearn.neighbors import KNeighborsClassifier
neighbors = KNeighborsClassifier(n_neighbors=1)
X = music[['loudness','duration']]
Y = music.jazz
neighbors.fit(X,Y)

neighbors.predict([[34,173]])

array([0])